/**
 * 本文件定义前后端共享的玩法常量，是协议和运行规则共同依赖的稳定来源。
 *
 * 维护时要同步检查客户端展示、服务端结算和配置编辑器，避免同一数值在多端分叉。
 */
import type { NumericRatioDivisors, NumericStats, RealmNumericTemplate } from '../../numeric';
import type { Attributes } from '../../attribute-types';
import type { BreakthroughItemRequirement } from '../../progression-view-types';
import { PlayerRealmStage, TechniqueRealm } from '../../cultivation-types';
import {
  addPartialNumericStats,
  cloneNumericRatioDivisors,
  cloneNumericStats,
  ensureNumericRatioDivisorsTemplate,
  ensureNumericStatsTemplateStats,
} from '../../numeric';

import {
  ATTR_KEYS,
  BASE_HIT,
  BASE_HP_REGEN_RATE,
  BASE_MAX_HP,
  BASE_MAX_QI,
  BASE_MAX_QI_OUTPUT_PER_TICK,
  BASE_PHYS_ATK,
  BASE_PHYS_DEF,
  BASE_QI_REGEN_RATE,
  BASE_SPELL_ATK,
  BASE_SPELL_DEF,
} from './attributes';
import { VIEW_RADIUS } from './world';

/**
 * 境界成长与境界模板常量。
 */

type RealmConfig = {
/**
 * name：名称名称或显示文本。
 */

  name: string;  
  /**
 * shortName：short名称名称或显示文本。
 */

  shortName: string;  
  /**
 * path：路径相关字段。
 */

  path: 'martial' | 'immortal';  
  /**
 * narrative：narrative相关字段。
 */

  narrative: string;  
  /**
 * progressToNext：进度ToNext相关字段。
 */

  progressToNext: number;  
  /**
 * attrBonus：attrBonu相关字段。
 */

  attrBonus: Partial<Attributes>;  
  /**
 * breakthroughItems：集合字段。
 */

  breakthroughItems: BreakthroughItemRequirement[];  
  /**
 * minTechniqueLevel：min功法等级数值。
 */

  minTechniqueLevel: number;  
  /**
 * minTechniqueRealm：min功法Realm相关字段。
 */

  minTechniqueRealm?: TechniqueRealm;
};

const ZERO_ELEMENT_STATS = {
  metal: 0,
  wood: 0,
  water: 0,
  fire: 0,
  earth: 0,
} as const;

/** FIXED_ELEMENT_DAMAGE_REDUCE_DIVISOR：FIXED元素DAMAGE REDUCE DIVISOR。 */
const FIXED_ELEMENT_DAMAGE_REDUCE_DIVISOR = 100;

function buildRealmNumericDelta(
  stage: PlayerRealmStage,
  stats: Partial<NumericStats>,
  ratioDivisorDelta: number,
): RealmNumericTemplate {
  return {
    stage,
    stats: ensureNumericStatsTemplateStats({
      maxHp: 0,
      maxQi: 0,
      physAtk: 0,
      spellAtk: 0,
      physDef: 0,
      spellDef: 0,
      hit: 0,
      dodge: 0,
      crit: 0,
      antiCrit: 0,
      critDamage: 0,
      breakPower: 0,
      resolvePower: 0,
      maxQiOutputPerTick: 0,
      qiRegenRate: 0,
      hpRegenRate: 0,
      cooldownSpeed: 0,
      auraCostReduce: 0,
      auraPowerRate: 0,
      playerExpRate: 0,
      techniqueExpRate: 0,
      realmExpPerTick: 0,
      techniqueExpPerTick: 0,
      lootRate: 0,
      rareLootRate: 0,
      viewRange: 0,
      moveSpeed: 0,
      extraAggroRate: 0,
      extraRange: 0,
      extraArea: 0,
      actionsPerTurn: 0,
      elementDamageBonus: { ...ZERO_ELEMENT_STATS },
      elementDamageReduce: { ...ZERO_ELEMENT_STATS },
      ...stats,
    }),
    ratioDivisors: ensureNumericRatioDivisorsTemplate({
      dodge: ratioDivisorDelta,
      crit: ratioDivisorDelta,
      breakPower: ratioDivisorDelta,
      resolvePower: ratioDivisorDelta,
      cooldownSpeed: ratioDivisorDelta,
      moveSpeed: ratioDivisorDelta,
      elementDamageReduce: { ...ZERO_ELEMENT_STATS },
    }),
  };
}

/** 默认玩家大境界。 */
export const DEFAULT_PLAYER_REALM_STAGE = PlayerRealmStage.Mortal;

/** 玩家大境界顺序。 */
export const PLAYER_REALM_ORDER: PlayerRealmStage[] = [
  PlayerRealmStage.Mortal,
  PlayerRealmStage.BodyTempering,
  PlayerRealmStage.BoneForging,
  PlayerRealmStage.Meridian,
  PlayerRealmStage.Innate,
  PlayerRealmStage.QiRefining,
  PlayerRealmStage.QiRefiningMiddle,
  PlayerRealmStage.QiRefiningLate,
  PlayerRealmStage.Foundation,
  PlayerRealmStage.FoundationMiddle,
  PlayerRealmStage.FoundationLate,
  PlayerRealmStage.GoldenCore,
  PlayerRealmStage.GoldenCoreMiddle,
  PlayerRealmStage.GoldenCoreLate,
  PlayerRealmStage.Nascent,
  PlayerRealmStage.NascentMiddle,
  PlayerRealmStage.NascentLate,
  PlayerRealmStage.SoulTransform,
  PlayerRealmStage.SoulTransformMiddle,
  PlayerRealmStage.SoulTransformLate,
  PlayerRealmStage.VoidRefine,
  PlayerRealmStage.VoidRefineMiddle,
  PlayerRealmStage.VoidRefineLate,
  PlayerRealmStage.BodyIntegration,
  PlayerRealmStage.BodyIntegrationMiddle,
  PlayerRealmStage.BodyIntegrationLate,
  PlayerRealmStage.Mahayana,
  PlayerRealmStage.MahayanaMiddle,
  PlayerRealmStage.MahayanaLate,
  PlayerRealmStage.Tribulation,
  PlayerRealmStage.TribulationMiddle,
  PlayerRealmStage.TribulationLate,
  PlayerRealmStage.Ascension,
];

/** 玩家大境界对应的等级区间。 */
export const PLAYER_REALM_STAGE_LEVEL_RANGES: Record<PlayerRealmStage, {
/**
 * levelFrom：等级From相关字段。
 */
 levelFrom: number;
 /**
 * levelTo：等级To相关字段。
 */
 levelTo: number }> = {
  [PlayerRealmStage.Mortal]: { levelFrom: 1, levelTo: 5 },
  [PlayerRealmStage.BodyTempering]: { levelFrom: 6, levelTo: 8 },
  [PlayerRealmStage.BoneForging]: { levelFrom: 9, levelTo: 11 },
  [PlayerRealmStage.Meridian]: { levelFrom: 12, levelTo: 15 },
  [PlayerRealmStage.Innate]: { levelFrom: 16, levelTo: 18 },
  [PlayerRealmStage.QiRefining]: { levelFrom: 19, levelTo: 22 },
  [PlayerRealmStage.QiRefiningMiddle]: { levelFrom: 23, levelTo: 26 },
  [PlayerRealmStage.QiRefiningLate]: { levelFrom: 27, levelTo: 30 },
  [PlayerRealmStage.Foundation]: { levelFrom: 31, levelTo: 34 },
  [PlayerRealmStage.FoundationMiddle]: { levelFrom: 35, levelTo: 38 },
  [PlayerRealmStage.FoundationLate]: { levelFrom: 39, levelTo: 42 },
  [PlayerRealmStage.GoldenCore]: { levelFrom: 43, levelTo: 46 },
  [PlayerRealmStage.GoldenCoreMiddle]: { levelFrom: 47, levelTo: 50 },
  [PlayerRealmStage.GoldenCoreLate]: { levelFrom: 51, levelTo: 54 },
  [PlayerRealmStage.Nascent]: { levelFrom: 55, levelTo: 58 },
  [PlayerRealmStage.NascentMiddle]: { levelFrom: 59, levelTo: 62 },
  [PlayerRealmStage.NascentLate]: { levelFrom: 63, levelTo: 66 },
  [PlayerRealmStage.SoulTransform]: { levelFrom: 67, levelTo: 70 },
  [PlayerRealmStage.SoulTransformMiddle]: { levelFrom: 71, levelTo: 74 },
  [PlayerRealmStage.SoulTransformLate]: { levelFrom: 75, levelTo: 78 },
  [PlayerRealmStage.VoidRefine]: { levelFrom: 79, levelTo: 82 },
  [PlayerRealmStage.VoidRefineMiddle]: { levelFrom: 83, levelTo: 86 },
  [PlayerRealmStage.VoidRefineLate]: { levelFrom: 87, levelTo: 90 },
  [PlayerRealmStage.BodyIntegration]: { levelFrom: 91, levelTo: 94 },
  [PlayerRealmStage.BodyIntegrationMiddle]: { levelFrom: 95, levelTo: 98 },
  [PlayerRealmStage.BodyIntegrationLate]: { levelFrom: 99, levelTo: 102 },
  [PlayerRealmStage.Mahayana]: { levelFrom: 103, levelTo: 106 },
  [PlayerRealmStage.MahayanaMiddle]: { levelFrom: 107, levelTo: 110 },
  [PlayerRealmStage.MahayanaLate]: { levelFrom: 111, levelTo: 114 },
  [PlayerRealmStage.Tribulation]: { levelFrom: 115, levelTo: 118 },
  [PlayerRealmStage.TribulationMiddle]: { levelFrom: 119, levelTo: 122 },
  [PlayerRealmStage.TribulationLate]: { levelFrom: 123, levelTo: 126 },
  [PlayerRealmStage.Ascension]: { levelFrom: 127, levelTo: 127 },
};

/** 武道到修仙的大境界配置。attrBonus 表示本大境界相对上一大境界的新增六维。 */
export const PLAYER_REALM_CONFIG: Record<PlayerRealmStage, RealmConfig> = {
  [PlayerRealmStage.Mortal]: {
    name: '凡俗境',
    shortName: '凡俗',
    path: 'martial',
    narrative: '筋骨未開，仍在江湖門檻之外，只能以勤練夯實根基。',
    progressToNext: 60,
    attrBonus: {},
    breakthroughItems: [
      { itemId: 'rat_tail', count: 3 },
      { itemId: 'boar_tusk', count: 1 },
    ],
    minTechniqueLevel: 1,
  },
  [PlayerRealmStage.BodyTempering]: {
    name: '淬體境',
    shortName: '淬體',
    path: 'martial',
    narrative: '以氣血反覆淬洗皮肉，凡軀漸能承載更重勁力。',
    progressToNext: 120,
    attrBonus: { constitution: 12, spirit: 2, perception: 4, talent: 4, strength: 8 },
    breakthroughItems: [
      { itemId: 'wolf_fang', count: 4 },
      { itemId: 'serpent_gall', count: 2 },
    ],
    minTechniqueLevel: 2,
    minTechniqueRealm: TechniqueRealm.Entry,
  },
  [PlayerRealmStage.BoneForging]: {
    name: '鍛骨境',
    shortName: '鍛骨',
    path: 'martial',
    narrative: '骨骼經受藥力與勁力淬鍊，氣血承載力顯著增長。',
    progressToNext: 180,
    attrBonus: { constitution: 8, spirit: 2, perception: 4, talent: 8, strength: 8 },
    breakthroughItems: [
      { itemId: 'black_iron_chunk', count: 4 },
      { itemId: 'crystal_dust', count: 3 },
    ],
    minTechniqueLevel: 4,
    minTechniqueRealm: TechniqueRealm.Minor,
  },
  [PlayerRealmStage.Meridian]: {
    name: '通脈境',
    shortName: '通脈',
    path: 'martial',
    narrative: '經脈漸通，勁力開始帶有內息性質，武道正向玄門靠攏。',
    progressToNext: 260,
    attrBonus: { constitution: 4, spirit: 8, perception: 10, talent: 6, strength: 6, meridians: 18 },
    breakthroughItems: [
      { itemId: 'black_iron_chunk', count: 6 },
      { itemId: 'rune_shard', count: 4 },
      { itemId: 'mine_signal_core', count: 1 },
    ],
    minTechniqueLevel: 6,
    minTechniqueRealm: TechniqueRealm.Minor,
  },
  [PlayerRealmStage.Innate]: {
    name: '先天境',
    shortName: '先天',
    path: 'martial',
    narrative: '內外歸一，先天一炁漸顯，是凡武邁向仙道的最後門檻。',
    progressToNext: 360,
    attrBonus: { constitution: 6, spirit: 18, perception: 12, talent: 12, strength: 8, meridians: 12 },
    breakthroughItems: [
      { itemId: 'rune_shard', count: 6 },
      { itemId: 'spirit_iron_fragment', count: 4 },
      { itemId: 'valley_core', count: 1 },
    ],
    minTechniqueLevel: 8,
    minTechniqueRealm: TechniqueRealm.Major,
  },
  [PlayerRealmStage.QiRefining]: {
    name: '練氣前期',
    shortName: '練氣前',
    path: 'immortal',
    narrative: '初引天地靈機入體，神識與經脈先行打開，正式踏入修仙序列。',
    progressToNext: 1040,
    attrBonus: { constitution: 10, spirit: 25, perception: 8, talent: 15, strength: 5, meridians: 30 },
    breakthroughItems: [
      { itemId: 'blood_feather', count: 6 },
      { itemId: 'demon_wolf_bone', count: 6 },
      { itemId: 'spirit_iron_fragment', count: 6 },
    ],
    minTechniqueLevel: 10,
    minTechniqueRealm: TechniqueRealm.Major,
  },
  [PlayerRealmStage.QiRefiningMiddle]: {
    name: '練氣中期',
    shortName: '練氣中',
    path: 'immortal',
    narrative: '靈機周流趨穩，神識、經脈與根骨同步增長，法術運轉更為順暢。',
    progressToNext: 1120,
    attrBonus: { constitution: 25, spirit: 25, perception: 22, talent: 25, strength: 23, meridians: 25 },
    breakthroughItems: [
      { itemId: 'blood_feather', count: 8 },
      { itemId: 'demon_wolf_bone', count: 8 },
      { itemId: 'spirit_iron_fragment', count: 8 },
    ],
    minTechniqueLevel: 11,
    minTechniqueRealm: TechniqueRealm.Major,
  },
  [PlayerRealmStage.QiRefiningLate]: {
    name: '練氣後期',
    shortName: '練氣後',
    path: 'immortal',
    narrative: '氣海漸滿，練氣一境歸於圓融，六維底子補足到百數之基。',
    progressToNext: 1200,
    attrBonus: { constitution: 35, spirit: 20, perception: 40, talent: 30, strength: 42, meridians: 15 },
    breakthroughItems: [
      { itemId: 'blood_feather', count: 10 },
      { itemId: 'demon_wolf_bone', count: 10 },
      { itemId: 'spirit_iron_fragment', count: 10 },
    ],
    minTechniqueLevel: 12,
    minTechniqueRealm: TechniqueRealm.Perfection,
  },
  [PlayerRealmStage.Foundation]: {
    name: '築基前期',
    shortName: '築基前',
    path: 'immortal',
    narrative: '道基初築，體魄、根骨與經脈開始承載更高層次的靈機。',
    progressToNext: 1240,
    attrBonus: { constitution: 25, spirit: 20, perception: 12, talent: 35, strength: 15, meridians: 30 },
    breakthroughItems: [],
    minTechniqueLevel: 12,
    minTechniqueRealm: TechniqueRealm.Perfection,
  },
  [PlayerRealmStage.FoundationMiddle]: {
    name: '築基中期',
    shortName: '築基中',
    path: 'immortal',
    narrative: '道基漸穩，根骨、神識與經脈繼續抬升，攻守根盤更厚。',
    progressToNext: 1320,
    attrBonus: { constitution: 35, spirit: 30, perception: 28, talent: 35, strength: 30, meridians: 35 },
    breakthroughItems: [],
    minTechniqueLevel: 13,
    minTechniqueRealm: TechniqueRealm.Perfection,
  },
  [PlayerRealmStage.FoundationLate]: {
    name: '築基後期',
    shortName: '築基後',
    path: 'immortal',
    narrative: '道基圓滿，六維百尺竿頭再進，後續更高境界已有根基。',
    progressToNext: 1400,
    attrBonus: { constitution: 40, spirit: 50, perception: 60, talent: 30, strength: 55, meridians: 35 },
    breakthroughItems: [],
    minTechniqueLevel: 14,
    minTechniqueRealm: TechniqueRealm.Perfection,
  },
  [PlayerRealmStage.GoldenCore]: {
    name: '金丹前期',
    shortName: '金丹前',
    path: 'immortal',
    narrative: '金丹初結，靈光內照，神識大漲，已入修仙中堅之列。',
    progressToNext: 2000,
    attrBonus: { constitution: 50, spirit: 70, perception: 40, talent: 45, strength: 40, meridians: 45 },
    breakthroughItems: [],
    minTechniqueLevel: 15,
    minTechniqueRealm: TechniqueRealm.Perfection,
  },
  [PlayerRealmStage.GoldenCoreMiddle]: {
    name: '金丹中期',
    shortName: '金丹中',
    path: 'immortal',
    narrative: '丹火溫養，內景漸明，六維穩步攀升。',
    progressToNext: 2200,
    attrBonus: { constitution: 55, spirit: 75, perception: 45, talent: 50, strength: 45, meridians: 50 },
    breakthroughItems: [],
    minTechniqueLevel: 16,
    minTechniqueRealm: TechniqueRealm.Perfection,
  },
  [PlayerRealmStage.GoldenCoreLate]: {
    name: '金丹後期',
    shortName: '金丹後',
    path: 'immortal',
    narrative: '一丹鎮府，百竅生輝，元嬰雛形隱現。',
    progressToNext: 2400,
    attrBonus: { constitution: 60, spirit: 80, perception: 50, talent: 55, strength: 50, meridians: 55 },
    breakthroughItems: [],
    minTechniqueLevel: 17,
    minTechniqueRealm: TechniqueRealm.Perfection,
  },
  [PlayerRealmStage.Nascent]: {
    name: '元嬰前期',
    shortName: '元嬰前',
    path: 'immortal',
    narrative: '元嬰初成，神魂可離體而存，壽元大增。',
    progressToNext: 3000,
    attrBonus: { constitution: 70, spirit: 100, perception: 60, talent: 65, strength: 55, meridians: 65 },
    breakthroughItems: [],
    minTechniqueLevel: 18,
    minTechniqueRealm: TechniqueRealm.Perfection,
  },
  [PlayerRealmStage.NascentMiddle]: {
    name: '元嬰中期',
    shortName: '元嬰中',
    path: 'immortal',
    narrative: '元嬰漸壯，神識覆蓋愈廣，法力愈厚。',
    progressToNext: 3300,
    attrBonus: { constitution: 75, spirit: 110, perception: 65, talent: 70, strength: 60, meridians: 70 },
    breakthroughItems: [],
    minTechniqueLevel: 19,
    minTechniqueRealm: TechniqueRealm.Perfection,
  },
  [PlayerRealmStage.NascentLate]: {
    name: '元嬰後期',
    shortName: '元嬰後',
    path: 'immortal',
    narrative: '元嬰圓滿，化神契機隱現，已是一方強者。',
    progressToNext: 3600,
    attrBonus: { constitution: 80, spirit: 120, perception: 70, talent: 75, strength: 65, meridians: 75 },
    breakthroughItems: [],
    minTechniqueLevel: 20,
    minTechniqueRealm: TechniqueRealm.Perfection,
  },
  [PlayerRealmStage.SoulTransform]: {
    name: '化神前期',
    shortName: '化神前',
    path: 'immortal',
    narrative: '元嬰化神，神魂與天地相感，法力質變。',
    progressToNext: 4500,
    attrBonus: { constitution: 90, spirit: 140, perception: 80, talent: 85, strength: 75, meridians: 85 },
    breakthroughItems: [],
    minTechniqueLevel: 21,
    minTechniqueRealm: TechniqueRealm.Perfection,
  },
  [PlayerRealmStage.SoulTransformMiddle]: {
    name: '化神中期',
    shortName: '化神中',
    path: 'immortal',
    narrative: '神魂愈凝，天地法則初窺門徑。',
    progressToNext: 5000,
    attrBonus: { constitution: 95, spirit: 150, perception: 85, talent: 90, strength: 80, meridians: 90 },
    breakthroughItems: [],
    minTechniqueLevel: 22,
    minTechniqueRealm: TechniqueRealm.Perfection,
  },
  [PlayerRealmStage.SoulTransformLate]: {
    name: '化神後期',
    shortName: '化神後',
    path: 'immortal',
    narrative: '化神圓滿，煉虛之路已在眼前。',
    progressToNext: 5500,
    attrBonus: { constitution: 100, spirit: 160, perception: 90, talent: 95, strength: 85, meridians: 95 },
    breakthroughItems: [],
    minTechniqueLevel: 23,
    minTechniqueRealm: TechniqueRealm.Perfection,
  },
  [PlayerRealmStage.VoidRefine]: {
    name: '煉虛前期',
    shortName: '煉虛前',
    path: 'immortal',
    narrative: '煉虛合道，虛空法則初成，已近大能之境。',
    progressToNext: 7000,
    attrBonus: { constitution: 110, spirit: 180, perception: 100, talent: 105, strength: 95, meridians: 105 },
    breakthroughItems: [],
    minTechniqueLevel: 24,
    minTechniqueRealm: TechniqueRealm.Perfection,
  },
  [PlayerRealmStage.VoidRefineMiddle]: {
    name: '煉虛中期',
    shortName: '煉虛中',
    path: 'immortal',
    narrative: '虛空法則漸深，合體契機隱現。',
    progressToNext: 7500,
    attrBonus: { constitution: 115, spirit: 190, perception: 105, talent: 110, strength: 100, meridians: 110 },
    breakthroughItems: [],
    minTechniqueLevel: 25,
    minTechniqueRealm: TechniqueRealm.Perfection,
  },
  [PlayerRealmStage.VoidRefineLate]: {
    name: '煉虛後期',
    shortName: '煉虛後',
    path: 'immortal',
    narrative: '煉虛圓滿，天人合一之境觸手可及。',
    progressToNext: 8000,
    attrBonus: { constitution: 120, spirit: 200, perception: 110, talent: 115, strength: 105, meridians: 115 },
    breakthroughItems: [],
    minTechniqueLevel: 26,
    minTechniqueRealm: TechniqueRealm.Perfection,
  },
  [PlayerRealmStage.BodyIntegration]: {
    name: '合體前期',
    shortName: '合體前',
    path: 'immortal',
    narrative: '天人合一，肉身與元神徹底融合，已是頂尖大能。',
    progressToNext: 10000,
    attrBonus: { constitution: 130, spirit: 220, perception: 120, talent: 125, strength: 115, meridians: 125 },
    breakthroughItems: [],
    minTechniqueLevel: 27,
    minTechniqueRealm: TechniqueRealm.Perfection,
  },
  [PlayerRealmStage.BodyIntegrationMiddle]: {
    name: '合體中期',
    shortName: '合體中',
    path: 'immortal',
    narrative: '合體漸深，大乘之路已現端倪。',
    progressToNext: 11000,
    attrBonus: { constitution: 140, spirit: 240, perception: 130, talent: 135, strength: 125, meridians: 135 },
    breakthroughItems: [],
    minTechniqueLevel: 28,
    minTechniqueRealm: TechniqueRealm.Perfection,
  },
  [PlayerRealmStage.BodyIntegrationLate]: {
    name: '合體後期',
    shortName: '合體後',
    path: 'immortal',
    narrative: '合體圓滿，大乘境界近在咫尺。',
    progressToNext: 12000,
    attrBonus: { constitution: 150, spirit: 260, perception: 140, talent: 145, strength: 135, meridians: 145 },
    breakthroughItems: [],
    minTechniqueLevel: 29,
    minTechniqueRealm: TechniqueRealm.Perfection,
  },
  [PlayerRealmStage.Mahayana]: {
    name: '大乘前期',
    shortName: '大乘前',
    path: 'immortal',
    narrative: '大乘初成，已是人間絕巔，渡劫飛昇指日可待。',
    progressToNext: 15000,
    attrBonus: { constitution: 160, spirit: 280, perception: 150, talent: 155, strength: 145, meridians: 155 },
    breakthroughItems: [],
    minTechniqueLevel: 30,
    minTechniqueRealm: TechniqueRealm.Perfection,
  },
  [PlayerRealmStage.MahayanaMiddle]: {
    name: '大乘中期',
    shortName: '大乘中',
    path: 'immortal',
    narrative: '大乘漸深，天劫之力已有感應。',
    progressToNext: 16000,
    attrBonus: { constitution: 170, spirit: 300, perception: 160, talent: 165, strength: 155, meridians: 165 },
    breakthroughItems: [],
    minTechniqueLevel: 31,
    minTechniqueRealm: TechniqueRealm.Perfection,
  },
  [PlayerRealmStage.MahayanaLate]: {
    name: '大乘後期',
    shortName: '大乘後',
    path: 'immortal',
    narrative: '大乘圓滿，渡劫在即，仙路將啟。',
    progressToNext: 18000,
    attrBonus: { constitution: 180, spirit: 320, perception: 170, talent: 175, strength: 165, meridians: 175 },
    breakthroughItems: [],
    minTechniqueLevel: 32,
    minTechniqueRealm: TechniqueRealm.Perfection,
  },
  [PlayerRealmStage.Tribulation]: {
    name: '渡劫前期',
    shortName: '渡劫前',
    path: 'immortal',
    narrative: '引動天劫，九死一生，飛昇之路正式開啟。',
    progressToNext: 22000,
    attrBonus: { constitution: 200, spirit: 350, perception: 180, talent: 185, strength: 175, meridians: 185 },
    breakthroughItems: [],
    minTechniqueLevel: 33,
    minTechniqueRealm: TechniqueRealm.Perfection,
  },
  [PlayerRealmStage.TribulationMiddle]: {
    name: '渡劫中期',
    shortName: '渡劫中',
    path: 'immortal',
    narrative: '天劫連連，每渡一劫，實力大增。',
    progressToNext: 25000,
    attrBonus: { constitution: 220, spirit: 380, perception: 190, talent: 195, strength: 185, meridians: 195 },
    breakthroughItems: [],
    minTechniqueLevel: 34,
    minTechniqueRealm: TechniqueRealm.Perfection,
  },
  [PlayerRealmStage.TribulationLate]: {
    name: '渡劫後期',
    shortName: '渡劫後',
    path: 'immortal',
    narrative: '九九歸一，最後一劫將至，飛昇在望。',
    progressToNext: 30000,
    attrBonus: { constitution: 250, spirit: 420, perception: 200, talent: 210, strength: 200, meridians: 210 },
    breakthroughItems: [],
    minTechniqueLevel: 35,
    minTechniqueRealm: TechniqueRealm.Perfection,
  },
  [PlayerRealmStage.Ascension]: {
    name: '飛昇',
    shortName: '飛昇',
    path: 'immortal',
    narrative: '渡盡天劫，白日飛昇，位列仙班。',
    progressToNext: 0,
    attrBonus: { constitution: 300, spirit: 500, perception: 250, talent: 250, strength: 250, meridians: 250 },
    breakthroughItems: [],
    minTechniqueLevel: 36,
    minTechniqueRealm: TechniqueRealm.Perfection,
  },
};

/** 按境界提供的数值模板增量与 RatioValue 除数增量。初始大境界为基础值，后续大境界为相对上一大境界的新增量。 */
export const PLAYER_REALM_NUMERIC_TEMPLATES: Record<PlayerRealmStage, RealmNumericTemplate> = {
  [PlayerRealmStage.Mortal]: {
    stage: PlayerRealmStage.Mortal,
    stats: ensureNumericStatsTemplateStats({
      maxHp: BASE_MAX_HP,
      maxQi: BASE_MAX_QI,
      physAtk: BASE_PHYS_ATK,
      spellAtk: BASE_SPELL_ATK,
      physDef: BASE_PHYS_DEF,
      spellDef: BASE_SPELL_DEF,
      hit: BASE_HIT,
      dodge: 0,
      crit: 0,
      antiCrit: 0,
      critDamage: 0,
      breakPower: 0,
      resolvePower: 0,
      maxQiOutputPerTick: BASE_MAX_QI_OUTPUT_PER_TICK,
      hpRegenRate: BASE_HP_REGEN_RATE,
      qiRegenRate: BASE_QI_REGEN_RATE,
      cooldownSpeed: 0,
      auraCostReduce: 0,
      auraPowerRate: 0,
      playerExpRate: 0,
      techniqueExpRate: 0,
      realmExpPerTick: 0,
      techniqueExpPerTick: 0,
      lootRate: 0,
      rareLootRate: 0,
      viewRange: VIEW_RADIUS,
      moveSpeed: 0,
      extraAggroRate: 0,
      extraRange: 0,
      extraArea: 0,
      actionsPerTurn: 1,
      elementDamageBonus: { ...ZERO_ELEMENT_STATS },
      elementDamageReduce: {
        metal: 0,
        wood: 0,
        water: 0,
        fire: 0,
        earth: 0,
      },
    }),
    ratioDivisors: ensureNumericRatioDivisorsTemplate({
      dodge: 100,
      crit: 100,
      breakPower: 100,
      resolvePower: 100,
      cooldownSpeed: 100,
      moveSpeed: 100,
      elementDamageReduce: {
        metal: FIXED_ELEMENT_DAMAGE_REDUCE_DIVISOR,
        wood: FIXED_ELEMENT_DAMAGE_REDUCE_DIVISOR,
        water: FIXED_ELEMENT_DAMAGE_REDUCE_DIVISOR,
        fire: FIXED_ELEMENT_DAMAGE_REDUCE_DIVISOR,
        earth: FIXED_ELEMENT_DAMAGE_REDUCE_DIVISOR,
      },
    }),
  },
  [PlayerRealmStage.BodyTempering]: buildRealmNumericDelta(PlayerRealmStage.BodyTempering, {
    maxHp: 25,
    hpRegenRate: 1.25,
    physAtk: 3,
    physDef: 3,
  }, 25),
  [PlayerRealmStage.BoneForging]: buildRealmNumericDelta(PlayerRealmStage.BoneForging, {
    maxHp: 20,
    hpRegenRate: 1,
    physAtk: 2,
    physDef: 3,
    spellDef: 1,
    breakPower: 1,
  }, 20),
  [PlayerRealmStage.Meridian]: buildRealmNumericDelta(PlayerRealmStage.Meridian, {
    maxHp: 15,
    maxQi: 25,
    hpRegenRate: 0.75,
    qiRegenRate: 1.25,
    spellAtk: 3,
    spellDef: 3,
    hit: 4,
    dodge: 2,
    breakPower: 2,
    resolvePower: 2,
    maxQiOutputPerTick: 3,
  }, 25),
  [PlayerRealmStage.Innate]: buildRealmNumericDelta(PlayerRealmStage.Innate, {
    maxHp: 20,
    maxQi: 15,
    hpRegenRate: 1,
    qiRegenRate: 0.75,
    physAtk: 3,
    spellAtk: 5,
    physDef: 2,
    spellDef: 4,
    hit: 4,
    dodge: 3,
    crit: 4,
    antiCrit: 4,
    breakPower: 2,
    resolvePower: 3,
    maxQiOutputPerTick: 2,
  }, 30),
  [PlayerRealmStage.QiRefining]: buildRealmNumericDelta(PlayerRealmStage.QiRefining, {
    maxHp: 25,
    maxQi: 35,
    hpRegenRate: 1.25,
    qiRegenRate: 1.75,
    physAtk: 2,
    spellAtk: 6,
    physDef: 2,
    spellDef: 5,
    hit: 3,
    dodge: 1,
    crit: 1,
    antiCrit: 2,
    breakPower: 1,
    resolvePower: 3,
    maxQiOutputPerTick: 3,
  }, 40),
  [PlayerRealmStage.QiRefiningMiddle]: buildRealmNumericDelta(PlayerRealmStage.QiRefiningMiddle, {
    maxHp: 30,
    maxQi: 40,
    hpRegenRate: 1.5,
    qiRegenRate: 2,
    physAtk: 3,
    spellAtk: 6,
    physDef: 3,
    spellDef: 5,
    hit: 4,
    dodge: 2,
    crit: 2,
    antiCrit: 2,
    breakPower: 2,
    resolvePower: 3,
    maxQiOutputPerTick: 4,
  }, 40),
  [PlayerRealmStage.QiRefiningLate]: buildRealmNumericDelta(PlayerRealmStage.QiRefiningLate, {
    maxHp: 35,
    maxQi: 55,
    hpRegenRate: 1.75,
    qiRegenRate: 2.75,
    physAtk: 3,
    spellAtk: 8,
    physDef: 3,
    spellDef: 7,
    hit: 5,
    dodge: 2,
    crit: 2,
    antiCrit: 2,
    breakPower: 4,
    resolvePower: 4,
    maxQiOutputPerTick: 4,
  }, 40),
  [PlayerRealmStage.Foundation]: buildRealmNumericDelta(PlayerRealmStage.Foundation, {
    maxHp: 55,
    maxQi: 65,
    hpRegenRate: 2.75,
    qiRegenRate: 3.25,
    physAtk: 6,
    spellAtk: 8,
    physDef: 7,
    spellDef: 8,
    hit: 5,
    dodge: 3,
    crit: 2,
    antiCrit: 4,
    breakPower: 4,
    resolvePower: 5,
    maxQiOutputPerTick: 6,
  }, 40),
  [PlayerRealmStage.FoundationMiddle]: buildRealmNumericDelta(PlayerRealmStage.FoundationMiddle, {
    maxHp: 75,
    maxQi: 80,
    hpRegenRate: 3.75,
    qiRegenRate: 4,
    physAtk: 7,
    spellAtk: 10,
    physDef: 8,
    spellDef: 10,
    hit: 7,
    dodge: 3,
    crit: 3,
    antiCrit: 4,
    breakPower: 6,
    resolvePower: 7,
    maxQiOutputPerTick: 6,
  }, 40),
  [PlayerRealmStage.FoundationLate]: buildRealmNumericDelta(PlayerRealmStage.FoundationLate, {
    maxHp: 100,
    maxQi: 105,
    hpRegenRate: 5,
    qiRegenRate: 5.25,
    physAtk: 9,
    spellAtk: 14,
    physDef: 11,
    spellDef: 15,
    hit: 8,
    dodge: 4,
    crit: 4,
    antiCrit: 5,
    breakPower: 8,
    resolvePower: 9,
    maxQiOutputPerTick: 8,
  }, 50),
  [PlayerRealmStage.GoldenCore]: buildRealmNumericDelta(PlayerRealmStage.GoldenCore, {
    maxHp: 130,
    maxQi: 140,
    hpRegenRate: 6.5,
    qiRegenRate: 7,
    physAtk: 12,
    spellAtk: 18,
    physDef: 14,
    spellDef: 20,
    hit: 10,
    dodge: 5,
    crit: 5,
    antiCrit: 6,
    breakPower: 10,
    resolvePower: 12,
    maxQiOutputPerTick: 10,
  }, 50),
  [PlayerRealmStage.GoldenCoreMiddle]: buildRealmNumericDelta(PlayerRealmStage.GoldenCoreMiddle, {
    maxHp: 150,
    maxQi: 160,
    hpRegenRate: 7.5,
    qiRegenRate: 8,
    physAtk: 14,
    spellAtk: 22,
    physDef: 16,
    spellDef: 24,
    hit: 12,
    dodge: 6,
    crit: 6,
    antiCrit: 7,
    breakPower: 12,
    resolvePower: 14,
    maxQiOutputPerTick: 12,
  }, 50),
  [PlayerRealmStage.GoldenCoreLate]: buildRealmNumericDelta(PlayerRealmStage.GoldenCoreLate, {
    maxHp: 180,
    maxQi: 190,
    hpRegenRate: 9,
    qiRegenRate: 9.5,
    physAtk: 16,
    spellAtk: 26,
    physDef: 18,
    spellDef: 28,
    hit: 14,
    dodge: 7,
    crit: 7,
    antiCrit: 8,
    breakPower: 14,
    resolvePower: 16,
    maxQiOutputPerTick: 14,
  }, 60),
  [PlayerRealmStage.Nascent]: buildRealmNumericDelta(PlayerRealmStage.Nascent, {
    maxHp: 220,
    maxQi: 240,
    hpRegenRate: 11,
    qiRegenRate: 12,
    physAtk: 20,
    spellAtk: 32,
    physDef: 22,
    spellDef: 34,
    hit: 16,
    dodge: 8,
    crit: 8,
    antiCrit: 10,
    breakPower: 18,
    resolvePower: 20,
    maxQiOutputPerTick: 16,
  }, 60),
  [PlayerRealmStage.NascentMiddle]: buildRealmNumericDelta(PlayerRealmStage.NascentMiddle, {
    maxHp: 260,
    maxQi: 280,
    hpRegenRate: 13,
    qiRegenRate: 14,
    physAtk: 24,
    spellAtk: 38,
    physDef: 26,
    spellDef: 40,
    hit: 18,
    dodge: 9,
    crit: 9,
    antiCrit: 11,
    breakPower: 20,
    resolvePower: 24,
    maxQiOutputPerTick: 18,
  }, 60),
  [PlayerRealmStage.NascentLate]: buildRealmNumericDelta(PlayerRealmStage.NascentLate, {
    maxHp: 300,
    maxQi: 320,
    hpRegenRate: 15,
    qiRegenRate: 16,
    physAtk: 28,
    spellAtk: 44,
    physDef: 30,
    spellDef: 46,
    hit: 20,
    dodge: 10,
    crit: 10,
    antiCrit: 12,
    breakPower: 24,
    resolvePower: 28,
    maxQiOutputPerTick: 20,
  }, 70),
  [PlayerRealmStage.SoulTransform]: buildRealmNumericDelta(PlayerRealmStage.SoulTransform, {
    maxHp: 360,
    maxQi: 400,
    hpRegenRate: 18,
    qiRegenRate: 20,
    physAtk: 34,
    spellAtk: 54,
    physDef: 36,
    spellDef: 56,
    hit: 24,
    dodge: 12,
    crit: 12,
    antiCrit: 14,
    breakPower: 28,
    resolvePower: 32,
    maxQiOutputPerTick: 24,
  }, 70),
  [PlayerRealmStage.SoulTransformMiddle]: buildRealmNumericDelta(PlayerRealmStage.SoulTransformMiddle, {
    maxHp: 420,
    maxQi: 460,
    hpRegenRate: 21,
    qiRegenRate: 23,
    physAtk: 40,
    spellAtk: 64,
    physDef: 42,
    spellDef: 66,
    hit: 28,
    dodge: 14,
    crit: 14,
    antiCrit: 16,
    breakPower: 32,
    resolvePower: 38,
    maxQiOutputPerTick: 28,
  }, 70),
  [PlayerRealmStage.SoulTransformLate]: buildRealmNumericDelta(PlayerRealmStage.SoulTransformLate, {
    maxHp: 500,
    maxQi: 540,
    hpRegenRate: 25,
    qiRegenRate: 27,
    physAtk: 48,
    spellAtk: 76,
    physDef: 50,
    spellDef: 78,
    hit: 32,
    dodge: 16,
    crit: 16,
    antiCrit: 18,
    breakPower: 38,
    resolvePower: 44,
    maxQiOutputPerTick: 32,
  }, 80),
  [PlayerRealmStage.VoidRefine]: buildRealmNumericDelta(PlayerRealmStage.VoidRefine, {
    maxHp: 600,
    maxQi: 660,
    hpRegenRate: 30,
    qiRegenRate: 33,
    physAtk: 58,
    spellAtk: 92,
    physDef: 60,
    spellDef: 94,
    hit: 38,
    dodge: 18,
    crit: 18,
    antiCrit: 20,
    breakPower: 44,
    resolvePower: 52,
    maxQiOutputPerTick: 38,
  }, 80),
  [PlayerRealmStage.VoidRefineMiddle]: buildRealmNumericDelta(PlayerRealmStage.VoidRefineMiddle, {
    maxHp: 700,
    maxQi: 780,
    hpRegenRate: 35,
    qiRegenRate: 39,
    physAtk: 68,
    spellAtk: 108,
    physDef: 70,
    spellDef: 110,
    hit: 44,
    dodge: 20,
    crit: 20,
    antiCrit: 22,
    breakPower: 52,
    resolvePower: 60,
    maxQiOutputPerTick: 44,
  }, 80),
  [PlayerRealmStage.VoidRefineLate]: buildRealmNumericDelta(PlayerRealmStage.VoidRefineLate, {
    maxHp: 820,
    maxQi: 900,
    hpRegenRate: 41,
    qiRegenRate: 45,
    physAtk: 80,
    spellAtk: 128,
    physDef: 82,
    spellDef: 130,
    hit: 50,
    dodge: 24,
    crit: 24,
    antiCrit: 26,
    breakPower: 60,
    resolvePower: 70,
    maxQiOutputPerTick: 50,
  }, 90),
  [PlayerRealmStage.BodyIntegration]: buildRealmNumericDelta(PlayerRealmStage.BodyIntegration, {
    maxHp: 1000,
    maxQi: 1100,
    hpRegenRate: 50,
    qiRegenRate: 55,
    physAtk: 96,
    spellAtk: 154,
    physDef: 98,
    spellDef: 156,
    hit: 60,
    dodge: 28,
    crit: 28,
    antiCrit: 30,
    breakPower: 70,
    resolvePower: 82,
    maxQiOutputPerTick: 60,
  }, 90),
  [PlayerRealmStage.BodyIntegrationMiddle]: buildRealmNumericDelta(PlayerRealmStage.BodyIntegrationMiddle, {
    maxHp: 1200,
    maxQi: 1320,
    hpRegenRate: 60,
    qiRegenRate: 66,
    physAtk: 114,
    spellAtk: 182,
    physDef: 116,
    spellDef: 184,
    hit: 70,
    dodge: 32,
    crit: 32,
    antiCrit: 34,
    breakPower: 82,
    resolvePower: 96,
    maxQiOutputPerTick: 70,
  }, 90),
  [PlayerRealmStage.BodyIntegrationLate]: buildRealmNumericDelta(PlayerRealmStage.BodyIntegrationLate, {
    maxHp: 1400,
    maxQi: 1540,
    hpRegenRate: 70,
    qiRegenRate: 77,
    physAtk: 134,
    spellAtk: 214,
    physDef: 136,
    spellDef: 216,
    hit: 82,
    dodge: 38,
    crit: 38,
    antiCrit: 40,
    breakPower: 96,
    resolvePower: 112,
    maxQiOutputPerTick: 82,
  }, 100),
  [PlayerRealmStage.Mahayana]: buildRealmNumericDelta(PlayerRealmStage.Mahayana, {
    maxHp: 1700,
    maxQi: 1870,
    hpRegenRate: 85,
    qiRegenRate: 93.5,
    physAtk: 160,
    spellAtk: 256,
    physDef: 162,
    spellDef: 258,
    hit: 96,
    dodge: 44,
    crit: 44,
    antiCrit: 46,
    breakPower: 112,
    resolvePower: 132,
    maxQiOutputPerTick: 96,
  }, 100),
  [PlayerRealmStage.MahayanaMiddle]: buildRealmNumericDelta(PlayerRealmStage.MahayanaMiddle, {
    maxHp: 2000,
    maxQi: 2200,
    hpRegenRate: 100,
    qiRegenRate: 110,
    physAtk: 190,
    spellAtk: 304,
    physDef: 192,
    spellDef: 306,
    hit: 112,
    dodge: 52,
    crit: 52,
    antiCrit: 54,
    breakPower: 132,
    resolvePower: 154,
    maxQiOutputPerTick: 112,
  }, 100),
  [PlayerRealmStage.MahayanaLate]: buildRealmNumericDelta(PlayerRealmStage.MahayanaLate, {
    maxHp: 2400,
    maxQi: 2640,
    hpRegenRate: 120,
    qiRegenRate: 132,
    physAtk: 226,
    spellAtk: 362,
    physDef: 228,
    spellDef: 364,
    hit: 130,
    dodge: 60,
    crit: 60,
    antiCrit: 62,
    breakPower: 154,
    resolvePower: 180,
    maxQiOutputPerTick: 130,
  }, 110),
  [PlayerRealmStage.Tribulation]: buildRealmNumericDelta(PlayerRealmStage.Tribulation, {
    maxHp: 2900,
    maxQi: 3200,
    hpRegenRate: 145,
    qiRegenRate: 160,
    physAtk: 270,
    spellAtk: 432,
    physDef: 272,
    spellDef: 434,
    hit: 152,
    dodge: 70,
    crit: 70,
    antiCrit: 72,
    breakPower: 180,
    resolvePower: 210,
    maxQiOutputPerTick: 152,
  }, 110),
  [PlayerRealmStage.TribulationMiddle]: buildRealmNumericDelta(PlayerRealmStage.TribulationMiddle, {
    maxHp: 3500,
    maxQi: 3850,
    hpRegenRate: 175,
    qiRegenRate: 192.5,
    physAtk: 322,
    spellAtk: 516,
    physDef: 324,
    spellDef: 518,
    hit: 178,
    dodge: 82,
    crit: 82,
    antiCrit: 84,
    breakPower: 210,
    resolvePower: 246,
    maxQiOutputPerTick: 178,
  }, 110),
  [PlayerRealmStage.TribulationLate]: buildRealmNumericDelta(PlayerRealmStage.TribulationLate, {
    maxHp: 4200,
    maxQi: 4620,
    hpRegenRate: 210,
    qiRegenRate: 231,
    physAtk: 386,
    spellAtk: 618,
    physDef: 388,
    spellDef: 620,
    hit: 208,
    dodge: 96,
    crit: 96,
    antiCrit: 98,
    breakPower: 246,
    resolvePower: 288,
    maxQiOutputPerTick: 208,
  }, 120),
  [PlayerRealmStage.Ascension]: buildRealmNumericDelta(PlayerRealmStage.Ascension, {
    maxHp: 5000,
    maxQi: 5500,
    hpRegenRate: 250,
    qiRegenRate: 275,
    physAtk: 460,
    spellAtk: 736,
    physDef: 462,
    spellDef: 738,
    hit: 250,
    dodge: 120,
    crit: 120,
    antiCrit: 120,
    breakPower: 300,
    resolvePower: 350,
    maxQiOutputPerTick: 250,
  }, 150),
};

const PLAYER_REALM_RATIO_DIVISOR_KEYS: Array<Exclude<keyof NumericRatioDivisors, 'elementDamageReduce'>> = [
  'dodge',
  'crit',
  'breakPower',
  'resolvePower',
  'cooldownSpeed',
  'moveSpeed',
];

/** 解析从凡俗境到目标大境界的累加段。 */
export function getPlayerRealmStagesThrough(stage: PlayerRealmStage | undefined): PlayerRealmStage[] {
  const index = PLAYER_REALM_ORDER.indexOf(stage ?? DEFAULT_PLAYER_REALM_STAGE);
  const normalizedIndex = index >= 0 ? index : PLAYER_REALM_ORDER.indexOf(DEFAULT_PLAYER_REALM_STAGE);
  return PLAYER_REALM_ORDER.slice(0, normalizedIndex + 1);
}

/** 累加到当前大境界后的六维基础加成。 */
export function resolvePlayerRealmAttributeBonus(stage: PlayerRealmStage | undefined): Attributes {
  const result = {
    constitution: 0,
    spirit: 0,
    perception: 0,
    talent: 0,
    strength: 0,
    meridians: 0,
  };
  for (const realmStage of getPlayerRealmStagesThrough(stage)) {
    const bonus = PLAYER_REALM_CONFIG[realmStage]?.attrBonus;
    if (!bonus) {
      continue;
    }
    for (const key of ATTR_KEYS) {
      result[key] += bonus[key] ?? 0;
    }
  }
  return result;
}

function addRatioDivisorDelta(target: NumericRatioDivisors, delta: NumericRatioDivisors): void {
  for (const key of PLAYER_REALM_RATIO_DIVISOR_KEYS) {
    target[key] += delta[key];
  }
  for (const element of ['metal', 'wood', 'water', 'fire', 'earth'] as const) {
    target.elementDamageReduce[element] += delta.elementDamageReduce[element];
  }
}

/** 累加到当前大境界后的完整数值模板。 */
export function resolvePlayerRealmNumericTemplate(stage: PlayerRealmStage | undefined): RealmNumericTemplate {
  const stages = getPlayerRealmStagesThrough(stage);
  const baseStage = stages[0] ?? DEFAULT_PLAYER_REALM_STAGE;
  const resolvedStage = stages[stages.length - 1] ?? DEFAULT_PLAYER_REALM_STAGE;
  const baseTemplate = PLAYER_REALM_NUMERIC_TEMPLATES[baseStage] ?? PLAYER_REALM_NUMERIC_TEMPLATES[DEFAULT_PLAYER_REALM_STAGE];
  const stats = cloneNumericStats(baseTemplate.stats);
  const ratioDivisors = cloneNumericRatioDivisors(baseTemplate.ratioDivisors);
  for (const realmStage of stages.slice(1)) {
    const template = PLAYER_REALM_NUMERIC_TEMPLATES[realmStage];
    if (!template) {
      continue;
    }
    addPartialNumericStats(stats, template.stats);
    addRatioDivisorDelta(ratioDivisors, template.ratioDivisors);
  }
  return {
    stage: resolvedStage,
    stats,
    ratioDivisors,
  };
}
