/**
 * 本文件定义前后端共享类型或纯规则函数，用于统一协议、配置和玩法计算口径。
 *
 * 维护时应保持无副作用、可在浏览器与 Node 环境同时使用，不引入单端专属依赖。
 */
/**
 * shared 包统一导出入口，前后端共用的类型、常量、工具函数均从此处导出。
 */
export * from './constants';
export * as gameplayConstants from './constants/gameplay';
export * as networkConstants from './constants/network';
export * as uiLabels from './constants/ui';
export * as visualConstants from './constants/visuals';
export * from './protocol';
export * from './api-contracts';
export * from './gm-custom-technique-contracts';
export * from './editor-item-catalog';
export * from './numeric';
export * from './automation-types';
export * from './action-combat-types';
export * from './cast-visuals';
export * from './activity-types';
export * from './attribute-types';
export * from './access-policy';
export * from './attr-detail-types';
export * from './client-core-request-types';
export * from './client-service-request-types';
export * from './client-social-admin-request-types';
export * from './protocol-envelope-types';
export * from './protocol-request-payload-types';
export * from './protocol-response-payload-types';
export * from './content-resolver-types';
export * from './cultivation-types';
export * from './crafting-types';
export * from './entity-detail-types';
export * from './gm-runtime-types';
export * from './gm-env-check-types';
export * from './item-runtime-types';
export * from './inventory-item-ref';
export * from './player-runtime-types';
export * from './technique';
export * from './technique-comprehension';
export * from './technique-aggregation';
export * from './technique-book';
export * as techniqueNormalization from './technique-normalization';
export * from './technique-arts-strength';
export * from './geometry';
export * from './direction';
export * from './pathfinding';
export * from './pathfinding-task';
export * from './path-codec';
export * from './targeting';
export * from './target-ref';
export * from './terrain';
export * from './map-layer-types';
export * from './craft-duration';
export * from './craft-effect-stats';
export * from './craft-elements';
export * from './craft-skill';
export * from './craft-success';
export * from './alchemy';
export * from './artifact';
export * from './enhancement';
export * from './technique-activity-types';
export * from './technique-activity-meta';
export * from './technique-activity-pipeline-types';
export * from './enhancement-cost';
export * from './display-number';
export * from './content-display-name';
export * from './value';
export * from './monster';
export * from './combat';
export * from './combat-event-types';
export * from './combat-relation';
export * from './item-stack';
export * from './network-protobuf';
export * from './network-protobuf-wire-helpers';
export * from './network-protobuf-tick-codecs';
export * from './network-protobuf-update-codecs';
export * from './network-protobuf-payload-codecs';
export * from './map-document';
export * from './map-rle';
export * from './map-groups';
export * from './aura';
export * from './qi';
export * from './formation-types';
export * from './sect-types';
export * from './social-types';
export * from './party-types';
export * from './age';
export * from './mail-types';
export * from './mail';
export * from './market-request';
export * from './content-config-validation';
export * from './build-material';
export * from './building-types';
export * from './time-chamber-types';
export * from './fengshui-types';
export * from './loot-view-types';
export * from './market-types';
export * from './observation-types';
export * from './progression-view-types';
export * from './quest-types';
export * from './skill-types';
export * from './detail-view-types';
export * from './session-sync-types';
export * from './service-sync-types';
export * from './notice-types';
export * from './runtime-event-bus.types';
export * from './template-registry-types';
export * from './offline-gain-types';
export * from './world-core-types';
export * from './world-space-layers';
export * from './leaderboard-types';
export * from './panel-update-types';
export * from './synced-panel-types';
export * from './synced-item-stack';
export * from './world-patch-types';
export * from './world-view-types';
export * from './market-price';
export * from './structured';
export * from './grapheme';
export * from './role-name';
export * from './name-visibility';
export * from './tutorial-mechanics.generated';
export * from './actor';
export * from './procgen';
