#!/usr/bin/env node
'use strict';

require('./load-local-runtime-env');

const path = require('node:path');
const { runVerificationSteps } = require('./verification-timing');

const repoRoot = path.resolve(__dirname, '..');
const env = {
  ...process.env,
  DATABASE_URL: '',
  SERVER_DATABASE_URL: '',
  DATABASE_POOLER_URL: '',
  SERVER_DATABASE_POOLER_URL: '',
  SERVER_ALLOW_UNREADY_TRAFFIC: '',
  SERVER_SMOKE_ALLOW_UNREADY: '',
  SERVER_SKIP_LOCAL_ENV_AUTOLOAD: '1',
};

const status = runVerificationSteps({
  command: 'pnpm verify:quick',
  gate: 'verify:quick',
  cwd: repoRoot,
  env,
  dbEnabled: false,
  shadowEnabled: Boolean(process.env.SERVER_SHADOW_URL || process.env.SERVER_URL),
  steps: [
    { label: 'server compile', args: ['--filter', '@mud/server', 'compile'] },
    { label: 'player-facing name boundaries', args: ['proof:player-facing-names'] },
    { label: 'runtime realm exp boundary', command: process.execPath, args: ['scripts/check-runtime-realm-exp-boundary.cjs'], shell: false },
    { label: 'production boundaries', args: ['--filter', '@mud/server', 'proof:production-boundaries'] },
    { label: 'release gate contract', args: ['proof:release-gates'] },
    {
      label: 'market stack signature item key',
      command: process.execPath,
      args: ['packages/server/dist/tools/market-stack-signature-item-key-smoke.js'],
      shell: false,
    },
    {
      label: 'offline gain duration',
      command: process.execPath,
      args: ['packages/server/dist/tools/offline-gain-duration-smoke.js'],
      shell: false,
    },
    {
      label: 'quick smoke',
      command: process.execPath,
      args: [
        'packages/server/dist/tools/run-stable-smoke-suite.js',
        '--case',
        'readiness-gate',
        '--case',
        'process-supervisor',
        '--case',
        'startup-config-resilience',
        '--case',
        'runtime',
        '--case',
        'session',
        '--case',
        'party-domain',
        '--case',
        'party-combat-reward',
        '--case',
        'gm-auth-token-revocation',
        '--case',
        'native-request-ip',
        '--case',
        'name-visibility',
        '--case',
        'native-auth-persistence-failure',
        '--case',
        'native-gm-player-domain-write',
        '--case',
        'native-database-restore-handoff',
        '--case',
        'offline-hanging-presence-import',
        '--case',
        'world-gateway-inventory-helper',
        '--case',
        'world-runtime-sect-application-page',
        '--case',
        'world-runtime-sect-member-profile',
        '--case',
        'world-runtime-sect',
        '--case',
        'formation-maintenance-job-handoff',
        '--case',
        'social-runtime-instance-name',
        '--case',
        'world-gateway-offline-gain-refresh',
        '--case',
        'offline-hanging-runtime-cleanup',
        '--case',
        'world-runtime-controller-lease-guard',
        '--case',
        'player-statistic-ledger-io',
        '--case',
        'player-runtime-dirty-domain',
        '--case',
        'inventory-item-instance-ref',
        '--case',
        'world-runtime-equipment',
        '--case',
        'world-runtime-aoi-cache-locality',
        '--case',
        'market-auction-expiry-return',
        '--case',
        'craft-persistence-dirty-domain',
        '--case',
        'technique-activity-completion',
        '--case',
        'technique-activity-statistics-hotpath',
        '--case',
        'technique-activity-queue-reorder',
        '--case',
        'world-gateway-craft-helper',
      ],
      shell: false,
    },
  ],
});

process.exit(status);
